AREA_WIDTH, AREA_HEIGHT = 800, 600
AREA_SIZE = (AREA_WIDTH, AREA_HEIGHT)
AREA_CENTRE = (AREA_WIDTH / 2, AREA_HEIGHT / 2)
ACTIONS = 9
COLORS = ['blue', 'green', 'red', 'yellow', 'pink', 'orange']

N_AGENTS = 6
START_RADIUS = 250.
SHRINK_SPEED = 1.

FPS = 60
